### ISSUE TITLE
CRUD 함수 정의 / 구조체 정하기

### ISSUE THREAD

**Issue by JewooJun** [OSS2022teamProject/miniProject#2]
CRUD 함수 정의 / 구조체 생각해봅시다.

**Comment by JewooJun** [comment]
일단 구조체부터 정의해봅시다. 제가 생각했을 때는 수입/지출을 나눌 수 있는 Int형 변수 하나 있으면 좋을 것 같고, 이름 , 가격, 카테고리 이렇게 하면 될 것 같은데 어떠신가요?

**Comment by hannahchun** [comment]
네 좋습니다. 
그리고, 수입 합계, 지출 합계를 계산하는 sum 함수도 하나 있으면 좋을 것 같습니다.

**Comment by JewooJun** [comment]
좋은 것 같습니다.
제가 방금 생각해보았는데 구조체에 비고란도 입력할 수 있도록 변수 만들면 괜찮을 것 같습니다.

**Comment by JewooJun** [comment]
그럼 제가 지금 말씀드렸던 부분(구조체 정의 / 함수 선언) 해서 올리도록 하겠습니다.
