### ISSUE TITLE
팀 프로젝트 주제

### ISSUE THREAD

**Issue by hannahchun** [OSS2022teamProject/miniProject#3]
저희 주제 선정은 예시에서 하는게 좋을까요? 아니면 이외의 다른 주제로 하는 것이 좋을까요?

**Comment by JewooJun** [comment]
예시 중에서 CAFE 디저트 자판기랑 가계부 프로그램이 괜찮아 보이네요

**Comment by hannahchun** [comment]
오 저도 Cafe 디저트 자판기 / 가계부 프로그램 둘다 괜찮게 보았습니다! cafe는 이전과 비슷하게 해서 가계부보다 간단하게는 구현할 수 있을 것 같네요. 가계부 프로그램은 조금더 구현할 것이 있어서 재밌게 할 수 있을 것 같습니다. 예를 들어서 카테고리별로 얼마나 지출이 있었는지도 볼 수 있게 구현하고, sum 기능을 만들어서 합도 볼 수 있으면 좋을 것 같네요.

**Comment by JewooJun** [comment]
CAFE 디저트 자판기는 이전 개인프로젝트랑 내용이 유사해서 가장 쉬울 것 같긴하네요

**Comment by hannahchun** [comment]
오 저도 Cafe 디저트 자판기 / 가계부 프로그램 둘다 괜찮게 보았습니다! cafe는 이전과 비슷하게 해서 가계부보다 간단하게는 구현할 수 있을 것 같네요. 가계부 프로그램은 조금더 구현할 것이 있어서 재밌게 할 수 있을 것 같습니다. 예를 들어서 카테고리별로 얼마나 지출이 있었는지도 볼 수 있게 구현하고, sum 기능을 만들어서 합도 볼 수 있으면 좋을 것 같네요.

**Comment by JewooJun** [comment]
네 저도 가계부 프로그램이 이전에 했던 개인 프로젝트랑 차별점이 있을 것 같아서 더 좋을 것 같아요!

**Comment by hannahchun** [comment]
그럼 주제 가계부 프로그램으로 정할까요?

**Comment by JewooJun** [comment]
네 그렇게 합시다 :)
