### ISSUE TITLE
CRUD 함수 정의 / 구조체 정하기

### ISSUE THREAD

**Issue by JewooJun** [OSS2022teamProject/miniProject#4]
구조체 하고 함수 정의해봐요.

**Comment by JewooJun** [comment]
제가 생각한 것은 구조체에서 수입과 지출을 받을 수 있는 것하고 이름, 가격, 카테고리 이정도 하면 될것 같은데 학우님 생각은 어떠세요?

**Comment by hannahchun** [comment]
네 괜찮은 것 같아요! 구조체에 비고란도 있으면 좋을 것 같아요!

**Comment by JewooJun** [comment]
네네 그럼 구조체는 그렇게 하도록 하겠습니다. 함수 부분에서는 기존의 mini project했던것이랑 비슷하게 하고 수입과 지출합계를 계산해주는 sum 함수 있으면 좋을 것 같은데 어떻게 생각하시나요?

**Comment by hannahchun** [comment]
네 이 부분은 전체 리스트 출력할 때 맨 아래에도 나오게 하면 될것 같아요!
나중에 카테고리 별로 sum을 계산하는 부분도 고려해볼까요?

**Comment by JewooJun** [comment]
오 그러면 너무 좋을 것 같아요. 그럼 제가 구조체하고 함수 정의해서 올리도록 하겠습니다.
