### ISSUE TITLE
데이터/기능 설계 보완

### ISSUE THREAD

**Issue by hannahchun** [OSS2022teamProject/miniProject#5]
구조체 멤버변수중 "비고란"을 "고정/변동 수입/지출"로 바꾸는 건 어떨까요?
![IMG_0582](https://user-images.githubusercontent.com/80413027/166138267-d9229b48-1315-4dce-bcd1-5ac692c2891a.jpg)

**Comment by hannahchun** [comment]
<구조체 맴버변수>
char fix[10];

<검색 기능> 
1차 - 수입/지출 검색
2차 - 고정/변동 검색

**Comment by hannahchun** [comment]
금액으로 검색할 때, 사용자 입장에서는 이게 나간 돈인지 들어온 돈인지를 구분하는 게 중요한 것 같아서, 
기존의 "금액으로 검색 기능"을 

<검색 기능>
1차 - 수입/지출 검색
2차 - 고정/변동 검색

으로 대체 하는 건 어떨까요?

**Comment by JewooJun** [comment]
네 비고란보다 수입과 고정 지출을 확인하는 것이 조금더 좋아보이네요. 제가 그럼 헤더파일 수정해서 올리도록 하겠습니다.

**Comment by JewooJun** [comment]
고정 지출을 다루는 변수 "fix"에선느 y/n으로 받으면 될 것 같습니다!

**Comment by JewooJun** [comment]
검색기능에서 가격 검색은 큰 의미가 있을 것 같지도 않고, 거의 사용하지 않을 것 같아 빼고 대신에 고정/변동 지출을 확인할 수 있는 searchFix라는 함수를 void형으로 선언하도록 하겠습니다.

**Comment by JewooJun** [comment]
구조체하고 함수 수정해서 올려놨습니다. 확인 부탁드립니다.

**Comment by hannahchun** [comment]
확인했습니다 감사합니다

**Comment by JewooJun** [comment]
카테고리명 변수 철자 틀린거 수정해서 업데이트 했습니다.

**Comment by hannahchun** [comment]
함수 쪽에도 해주실 수 있을까요?

**Comment by JewooJun** [comment]
아 제가 위에꺼만 봤네요ㅠ 수정후 업데이트 했습니다.
