### ISSUE TITLE
CRUD 함수 구현, 코딩 관련 issue

### ISSUE THREAD

**Issue by JewooJun** [OSS2022teamProject/miniProject#6]
listProduct 에서 나오는 List (No. 카테고리 항목명 가격 고정/변동 수입/지출) 순서대로 구조체 순서 바꾸면 보기 좋을 것 같은데 바꿔도 괜찮을까요?

**Comment by hannahchun** [comment]
네 그렇게 하면 더 깔끔할 것 같습니다

**Comment by JewooJun** [comment]
CRUD 함수 구현 다 해서 올리도록 하겠습니다. 학우님께서는 main 함수 작성한거 올려주실래요?

**Comment by hannahchun** [comment]
네 알겠습니다

**Comment by JewooJun** [comment]
money.c 파일 올렸습니다. 혹시 수정할 것이 있을까요?

**Comment by JewooJun** [comment]
지금 깃이 꼬여서 다시 강제로 push해서 돌려놨습니다. main 함수 다시 올리시면 될 것 같습니다!

**Comment by hannahchun** [comment]
moneybook.c에서 항목 조회 시, 수입 지출 여부에 따라 sum을 계산하는 기능을 추가했습니다.

**Comment by JewooJun** [comment]
제가 검색기능 추가하는 함수 구현해서 올리도록 하겠습니다! 아 그리고 지금 sum 기능추가한것 안올라와서 올려주시면 될 것 같아요

**Comment by JewooJun** [comment]
아 아직 구현하지 않은건가요?

**Comment by JewooJun** [comment]
이번에는 제가 검색기능 전부 구현하고 학우님께서는 파일 입/출력부분 함수 구현해주셔서 올리고 나머지 같이 손보면 좋을 것 같아요

**Comment by hannahchun** [comment]
네 알겠습니다 
오늘 화요일 밤까지 마감이었던 과제가 있어서
수요일에 제가 sum 구현하고 파일 입출력 수정해서 올리겠습니다

**Comment by hannahchun** [comment]
sum 함수
파일 입출력
항목 조회 시, 서식 통일
모두 github에 push 했습니다! 

그리고, sum 함수 구현 시, 좀 더 편하게 하려고, 배열의 개수를 담는 매개 변수 int cnt 하나 추가했습니다.

**Comment by JewooJun** [comment]
네 너무 좋습니다
방금 검색 함수 구현 다 해서 올려드렸습니다. 확인 한번 부탁드릴게요.

**Comment by hannahchun** [comment]
확인해봤는데 검색함수 하나를 이용하면 종료가 되어버리네요ㅠㅠ 
학우님 하실 때는 안 그랬나요?

**Comment by JewooJun** [comment]
제가 확인이 늦었네요ㅠ 제가 오늘 일정마치고 다시 확인해보고 연락드리겠습니다.
